AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DB_HOST: materun-dev.cfrj5305jcit.eu-north-1.rds.amazonaws.com
        DB_USER: admin
        DB_PASS: wjqDStkjWiVRQzCDxxgO
        DB_NAME: materun
Resources:
  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/070241f238140b6216e04eabfc4b2928
      Handler: create-account
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /create-account
            Method: post
  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/303074d8fd1e01f5bce8cd2ddfbc6bca
      Handler: sign-in
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /sign-in
            Method: post
  AccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/9f7e70c37c38cac2b50a565fbc18cdd9
      Handler: account
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /account
            Method: post
  CreateWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/ff97ebaf7f81a4167942799c33fbcb30
      Handler: create-workout
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /workouts
            Method: post
