AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DB_HOST: materun-dev.cfrj5305jcit.eu-north-1.rds.amazonaws.com
        DB_USER: admin
        DB_PASS: wjqDStkjWiVRQzCDxxgO
        DB_NAME: materun
Resources:
  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/6543a5ebdf41a356dcbf12a26b3be7ee
      Handler: create-account
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /create-account
            Method: post
  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/18d235f596a71bbed06d213385cf9754
      Handler: sign-in
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /sign-in
            Method: post
  AccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/4facd46be94472e4149297e9037eef61
      Handler: account
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /account
            Method: post
  CreateWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/bea3b11fec309914450b8f58da66033d
      Handler: create-workout
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /workouts
            Method: post
