AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'sam-app

  Sample SAM Template for sam-app

  '
Globals:
  Function:
    Timeout: 30
    Environment:
      Variables:
        DB_HOST: materun-dev.cfrj5305jcit.eu-north-1.rds.amazonaws.com
        DB_USER: admin
        DB_PASS: wjqDStkjWiVRQzCDxxgO
        DB_NAME: materun
Resources:
  CreateAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/18c5d0ff31f95a7e8d15c45ed8722dbd
      Handler: create-account
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /create-account
            Method: post
  SignInFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/85937e77ec41f1042dde128aa1c8de37
      Handler: sign-in
      Runtime: go1.x
      MemorySize: 2048
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /sign-in
            Method: post
  AccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/8de1d5c8fca51f97f050dd706afbd130
      Handler: account
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /account
            Method: post
  ListWorkoutsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/8d32047fa88b2b5816491ebc90132814
      Handler: list-workouts
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /list-workouts
            Method: post
  CreateWorkoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://materun-api-artifacts/7bd143efaf37ac5f62078d8ecafe6381
      Handler: create-workout
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
        - sg-4fc2d527
        SubnetIds:
        - subnet-8705cbee
        - subnet-ae050ee4
        - subnet-e5678e9e
      Events:
        CreateAccount:
          Type: Api
          Properties:
            Path: /workouts
            Method: post
